# Generated by Django 5.0 on 2024-03-03 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payments', '0002_userpayments_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='payment_bool',
            new_name='subscription_status',
        ),
        migrations.AddField(
            model_name='userpayments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
