# Generated by Django 5.0 on 2024-03-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payments', '0003_rename_payment_bool_userpayments_subscription_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='stripe_customer_id',
            new_name='stripe_customer',
        ),
        migrations.AddField(
            model_name='userpayments',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
