# Generated by Django 5.0 on 2024-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_payments', '0004_rename_stripe_customer_id_userpayments_stripe_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='stripe_checkout_id',
            new_name='stripe_subscription_id',
        ),
    ]
