# Generated by Django 5.0 on 2024-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payments', '0005_rename_stripe_checkout_id_userpayments_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='subscription_number',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
