# Generated by Django 5.0 on 2024-01-26 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "image_path",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core_functions_mars/functions/saved_images",
                    ),
                ),
                (
                    "user_input_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core_functions_mars/functions/downloaded_images",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
        ),
    ]
