# Generated by Django 5.0 on 2024-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='saved_images'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_input_image',
            field=models.ImageField(blank=True, null=True, upload_to='downloaded_images'),
        ),
    ]
