# Generated by Django 5.0 on 2024-01-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
