# Generated by Django 5.0 on 2024-01-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_alter_chat_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="image_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
