# Generated by Django 5.0 on 2024-01-07 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_alter_chat_image_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="django_chatbot/core_functions_mars/functions/saved_images",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
