# Generated by Django 5.0 on 2024-01-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_alter_chat_image_path_alter_chat_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="core_functions_mars/functions/saved_images",
            ),
        ),
    ]
