# Generated by Django 5.0 on 2024-01-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0007_alter_chat_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="user_input_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="core_functions_mars/functions/downloaded_images",
            ),
        ),
    ]
